// MY OWN CONFIG
function setOwlPlugin(){
    $('.owl-carousel-1').owlCarousel({
        loop:true,
        margin:10,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    })
    $('.owl-carousel-2').owlCarousel({
        loop:true,
        margin:10,
        nav:false,
        dots:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
        
    })
    $('.owl-carousel-products').owlCarousel({
        loop:true,
        stagePadding:50,
        margin:10,
        nav:true,
        dots:false,
        navContainer:'.nav-container-products',
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:6
            }
        }
    })
}