// MY OWN CONFIG
export default function setOwlPlugin(){
    $('.owl-carousel-1').owlCarousel({
        loop:true,
        margin:10,
        nav:false,
        dots:true,
        items:1
    })
    $('.owl-carousel-2').owlCarousel({
        margin:30,
        nav:false,
        loop:true,
        responsive:{
            0:{
                items:2,
                center:true,
                margin:10,
                dots:true,
            },
            768:{
                items:2,
                center:true,
                dots:false,
            },
            1000:{
                items:3,
            }
        }
        
    })
    $('.owl-carousel-products').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        center:true,
        dots:false,
        navContainer:'.owl-carousel-products',
        responsive:{
            0:{
                items:2
            },
            600:{
                items:4
            },
            1000:{
                items:6
            }
        }
    })
}